# -*- coding: utf-8 -*-
"""MIS515_homework4_part_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12d0F-4vhAnymkEdecrVjx6hPDhsV5v_A
"""

## PART - 2 ##
# This program, loads the decision tree model to predict if the loan will be funded or not based on user inputs

# Importing required libraries
import joblib
import sklearn.metrics as sk_m
import sklearn.tree as sk_t

repeat = "yes"
while repeat == "yes":

    # Asks name of decision tree file to load
    name_of_tree = (input("Enter the name of the decision tree file to load: ")).lower().strip()
    print()

    # Checks if file is kiva_decision_tree.joblib
    if name_of_tree == "kiva_decision_tree.joblib":
        # Loads the decision tree
        decision_tree = joblib.load(name_of_tree)

        # Asks user to enter the values of variables
        check = 0
        try:
            length = float(input("Enter the length of the post to predict: "))
            check = check + 1
        except:
            print("Sorry, you entered an invalid value.")

        if check == 1:
            try:
                number_of_pictures = int(input("Enter the number of pictures in the post: "))
                check = check + 1
            except:
                print("Sorry, you entered an invalid value.")
        
        if check == 2:
            try:
                loan_amount = float(input("Enter the loan amount requested: "))
                check = check + 1
            except:
                print("Sorry, you entered an invalid value.")

        if check == 3:
            bonus_credit_eligibility = input("Enter the bonus credit eligibility (yes/no): ")
            bonus_credit_eligibility = bonus_credit_eligibility.lower().strip()

            # Converts string to numeric values    
            if bonus_credit_eligibility == "yes":
                bonus_credit_eligibility = 1
                check = check + 1
            elif bonus_credit_eligibility == "no":
                bonus_credit_eligibility = 0
                check = check + 1
            else:
                print("Please enter valid input (yes/no)")

        if check == 4:        
            user_favorite_post = input("Enter whether the post was a user favorite post (yes/no): ")
            user_favorite_post = user_favorite_post.lower().strip()

            # Converts string to numeric values 
            if user_favorite_post == "yes":
                user_favorite_post = 1
                check = check + 1
            elif user_favorite_post == "no":
                user_favorite_post = 0
                check = check + 1
            else:
                print("Please enter valid input (yes/no)")

        if check == 5:
            # Creates a 2D list 
            x = [[length, number_of_pictures, loan_amount, bonus_credit_eligibility, user_favorite_post]]

            # Predictions
            prediction = decision_tree.predict(x)

            # Prints output
            print()
            if prediction == 1:
                print("Based on the decision tree, the loan will be funded.")
            else:
                print("Based on the decision tree, the loan will not be funded.")

        else: 
            print("Sorry, please enter the valid inputs to predict loan status")

    # Prints a messege if user enters file name other than kiva_decision_tree.joblib
    else:
        print("Sorry, this tree can not be loaded")

    # Asks user for repeatative prediction
    print()   
    repeat = (input("Would you like to predict another loan status (funded/expired)? ")).lower().strip()
    print()