# -*- coding: utf-8 -*-
"""Homework_1_MIS515.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PzfUbgenGvf2e2eoEbcRf0HuMbxIUSDf
"""

# This program will analyze the baby names by comparing two names by thier popularity and also provides year in which a given name is more popular.  

# Import CSV file of USA baby names and CSV library
!wget -nc http://dgoldberg.sdsu.edu/515/usa_baby_names.csv

import csv

# Welcome message
print("Welcome to the baby name analyzer!")
print("\n")

# If the user wants to perform several analysis or compare several names, the while loop runs analysis until the user wants to stop.
repeat_analysis = "yes"

while repeat_analysis.lower().strip() == 'yes':

    # Asks user what type of analysis they would like to perform
    analysis_type = input("What analysis would you like to run (name comparison/maximum popularity)? ")

    # If the user chooses name comparison, he is asked to enter two names
    if analysis_type.lower().strip() == "name comparison":
        first_name = input("Enter the first name to analyze: ")
        second_name = input("Enter the second name to analyze: ")

        # Searches for two names in CSV file and computes the sum of frequencies of two name in all the years 
        with open("usa_baby_names.csv", "r") as file:
            reader = csv.reader(file)

            # freq_1 for first name and freq_2 for second name
            freq_1 = 0
            freq_2 = 0

            for line in reader:
                name = line[0]
                frequency = int(line[2])

                if first_name == name:
                    freq_1 = freq_1 + frequency

                if second_name == name:
                    freq_2 = freq_2 + frequency

        # Compares the popularity of two names and prints the result.    
        if freq_1 > freq_2:
            print(f"{first_name} was more popular than {second_name} ({freq_1} to {freq_2})!")
        elif freq_2 > freq_1:
            print(f"{second_name} was more popular than {first_name} ({freq_2} to {freq_1})!")
        else:
            print("Either you entered the same names or both the names are equally popular")



    # If the user chooses maximum popularity, he is asked to enter a name
    elif analysis_type.lower().strip() == "maximum popularity":
        search_name = input("Enter the name to analyze:")

        # Searches for the name entered by user in CSV file.
        with open("usa_baby_names.csv", "r") as file:
            reader = csv.reader(file)

            # Created a dictionary frequency_dict to store the frequency of the given name in several years with year as it's key.
            frequency_dict = {} 

            for line in reader:
                name = line[0]
                year = line[1]
                frequency = int(line[2])

                if search_name == name:
                    frequency_dict[year] = frequency

            # Finds the year when the given name was more popular.
            list_frequency = []
            list_frequency = frequency_dict.values()
            max_frequency = max(list_frequency)

            for key in frequency_dict:
                if frequency_dict[key] == max_frequency:
                    popular_year = key

        # Prints the result.    
        print(f"{search_name} was most popular in {popular_year} with a frequency of {max_frequency}")

    

    # If the user did not make the correct choice of analysis type.
    else:
        print("Sorry, that type of analysis is not supported.")
    

    # Asks user whether they want run another analysis.
    print("\n")
    repeat_analysis = input("Would you like to run another analysis (yes/no)? ")
    print("\n")